### ISSUE TITLE
Handle reconnection when Bluetooth is disabled

### ISSUE THREAD

**Issue by jhud** [Smartphone-Companions/ESP32NotificationsLib#1]
The library should start advertising again if the Bluetooth drops out.

**Comment by Petros144** [comment]
Hi Jhud!

Thank you for the great implementation of ANCS! I played a bit with it and if i disable BT on my iPhone and enable it again, it wont reconnect automaticly.

is there a solution for this problem?

**Comment by jhud** [comment]
> Hi Jhud!
> 
> Thank you for the great implementation of ANCS! I played a bit with it and if i disable BT on my iPhone and enable it again, it wont reconnect automaticly.
> 
> is there a solution for this problem?

Hi, Petros, thanks! That's what this bug is about... I'm going to look at any and all reconnection issues soon.
