### ISSUE TITLE
Device not Found in iOS menu

### ISSUE THREAD

**Issue by Petros144** [Smartphone-Companions/ESP32NotificationsLib#4]
Hi JHud,

I´ve Tested the latest Version, and there is one major problem:

the ESP wont show up in the iOS Bluetooth menu as Device. 
With the NRF Connect app I can see it and connect, than it shows up. 
After Restart, the device is still invisible in the BT menu.

this only happens when you force the Phone to "forget" the device.

The problem was not present in the last version without the Categorys.

**Comment by jhud** [comment]
Looks like there was some race condition when debugging logging was turned off. I could reproduce it, and it's fixed for me in the latest version.

**Comment by Petros144** [comment]
Working now! Thank you!!!
